name: Build executable for release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: ⚙️ Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@7547f78e92afc13352b946775483c5392b7fda10 # v1.2.5
        with:
          path: 'platform-tools-installer.iss'

      - name: ✅ Attest artifacts
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1.4.4
        # See https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
        with:
          subject-path: Output/platform-tools-installer.exe

      - name: ⬆️ Upload files to release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: 'Output/platform-tools-installer.exe'
