name: Build executable for release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ⚙️ Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@7547f78e92afc13352b946775483c5392b7fda10 # v1.2.5
        with:
          path: 'platform-tools-installer.iss'

      - name: ✅ Attest artifacts
        uses: actions/attest-build-provenance@619dbb2e03e0189af0c55118e7d3c5e129e99726 # v2.0.0
        # See https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
        with:
          subject-path: Output/platform-tools-installer.exe

      - name: ⬆️ Upload files to release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2
        with:
          files: 'Output/platform-tools-installer.exe'
